[project]
name = "entregable-modelo-basico"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.9",
    "pillow>=12.0.0",
    "pytest>=9.0.2",
    "pytest-django>=4.11.1",
    "whitenoise" = "*"
]
